import Navigation from "./components/navigation";

export const metadata = {
  title: {
    template: "%s | NextJS project",
    default: "Loading...",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        <br />
        {children}
      </body>
    </html>
  );
}
